### ISSUE TITLE
Issue with back button and turbolinks 5

### ISSUE THREAD

**Issue by borisrorsvort** [rstacruz/onmount#134]
Everything seems to work fine except when hitting the back button after a Turbolink visit
Consider this code:

```
import $ from 'jquery'
import SimpleMDE from 'simplemde';

$.onmount('#markitup', function () {
  if ($("#markitup").length === 1) {
    var simplemde = new SimpleMDE({ element: $("#markitup")[0] });
  }
})

$(document).on('ready turbolinks:load', function () { $.onmount() })
$(document).on('turbolinks:before-render', function () { $.onmount.teardown() })

```

SimpleMDE is never triggered twice while changing the page (clicking on links) except when pressing the back button

**Comment by rstacruz** [comment]
Would appreciate some help here. I'm not knee-deep into Turbolinks internals quite yet.

**Comment by rstacruz** [comment]
Oh I got this. You need an exit handler for that to clean up (undo) what SimpleMDE has done.
