### ISSUE TITLE
init function not ran on already existing nodes matching the selector

### ISSUE THREAD

**Issue by farmisen** [rstacruz/onmount#208]
Hello,

With my current setting, `onmount()` is called when the document DOMContentLoaded is fired. At this point the DOM node I am interested in is already present in the page but if I call `onmount('[data-js-behavior-name]', function init() {...})` then the init function is not called until the next `onmount()` or `onmount('[data-js-behavior-name]')` call. Would it not make sense for `onmount(selector, init)` to call init on each of the selector matching DOM elements and not wait for the next polling call?

**Comment by rstacruz** [comment]
> Would it not make sense for onmount(selector, init) to call init on each of the selector matching DOM elements and not wait for the next polling call?

Hey, sorry I'm going to have to disagree on this. Imagine an app where you have 300 onmount behaviors:

```js
onmount('[data-js-behavior-one]', ...)
onmount('[data-js-behavior-two]', ...)
onmount('[data-js-behavior-three]', ...)
...
onmount('[data-js-behavior-three-hundred]', ...)
onmount()
```

Calling `onmount()` once will be less of a bottleneck than doing `onmount()` every step of the way.

This is typically not a problem, since binding the polling function is usually done this way:


```js
onmount('[data-js-behavior-one]', ...)
onmount('[data-js-behavior-two]', ...)
onmount('[data-js-behavior-three]', ...)
...
onmount('[data-js-behavior-three-hundred]', ...)

...

import ready from 'document-ready'

ready(() => { onmount() })

document.addEventListener('page:load', () => { onmount() })
document.addEventListener('page:change', () => { onmount() })
```


Nonetheless, thanks for your contribution!
