### ISSUE TITLE
Strange issue - onmount doesn't work

### ISSUE THREAD

**Issue by r007** [rstacruz/onmount#219]
Hi there,

First of all, thanks for your useful JS guide. I wanted to ask for your advice - for some reason, onmount doesn't work for me (maybe I'm missing something obvious). Here's the HTML page:
```html
<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">

  <title>Testing onmount</title>
  <meta name="description" content="Testing onmount">
  <meta name="author" content="Sergey Monin">

</head>

<body>
  <div class="test">Test element</div>
  <script src="bundle.js"></script>
</body>
</html>
```
Here's the js file:
```js
import onmount from 'onmount'

onmount('.test', function () {
    console.log('test passed');
    // Silence... nothing in console (in both Firefox / Chrome).
})
```
And... nothing.

I tried everything:

1. Used ```var onmount = require('onmount')``` instead of **import**.
2. Tried to import jQuery and then used ```$.onmount```.
3. Tried to replace class with data-attribute ```data-js-test``` as recommended in your guide.
4. Tried to load onmount.js as independent script and then used ```window.onmount();```

Here's the generated [bundle.js](https://pastebin.com/raw/uASucCxj). And here's my gulp task: 

```js
// Compile scripts
gulp.task('scripts-compile', function () {
  const b = browserify({
    entries: 'app.js',
    transform: babelify,
    debug: true
  });

  return b.bundle()
    .pipe(source('bundle.js'))
    .pipe(buffer())
    .pipe(gulp.dest(config.dest))
});
```
Package.json config:
```json
"browserify": {
    "transform": [
      [
        "babelify",
        {
          "presets": [
            "@babel/preset-env"
          ]
        }
      ]
    ]
  }
```
Eslintrc.json
```json
{
  "parserOptions": {
    "ecmaVersion": 2018,
    "ecmaFeatures": {
      "jsx": true
    },
    "sourceType": "module"
  },

  "env": {
    "browser": true,
    "commonjs": true,
    "es6": true,
    "jquery": true
  },

  "plugins": [
    "import",
    "node",
    "promise",
    "standard"
  ],

  "globals": {
    "document": false,
    "navigator": false,
    "window": false
  }
}
```
Any idea of how to make it work?

**Comment by r007** [comment]
Oh... nevermind. I think I found the solution - forgot to call ```onmount()``` in the end.

**Comment by rstacruz** [comment]
Glad you got it sorted out!

If you're using this for React, I suggest looking at [remount](http://github.com/rstacruz/remount) instead.

**Comment by r007** [comment]
@rstacruz not quite yet. Still trying to figure out the namespace issue, for example:
```js
// It works.
onmount();

// Doesn't work, throws an error,
// Something like "n.default.onmount is not a function"
$(document).on('ready show.bs closed.bs load page:change', onmount);
```
I'm not very familiar with ES6, just trying to improve the JS code of my [wordpress theme](http://demo.startuplywp.com/). This approach has too many issues right now. For example jQuery is not visible unless I do the ```npm install jquery --save-dev``` and then ```import $ from 'jquery'```. But it leads ti the duplicated code.

I'm thinking, maybe will be better to concatenate the scripts. Without babel/ES6, just plain old JavaScript.
