### ISSUE TITLE
Doesn't work with latest turbolinks

### ISSUE THREAD

**Issue by mintuhouse** [rstacruz/onmount#47]
I have tried to use [TL5](https://github.com/basecamp/turbolinks/tree/v5) (which is most likely going to be bundled with [rails 5](https://github.com/rails/turbolinks/issues/628)) with onmount but it doesn't seem to auto-initialize components. 
One of the difference I found is that the DOM elements from cached pages are still accessible on any page.

I added the initializer as described in [rails doc](https://github.com/rstacruz/onmount/blob/master/docs/rails.md)

P.S.: You may already be aware of it, after all its you(rstacruz) who initiated the discussion. I want to know if there are any plans to support it?

**Comment by rstacruz** [comment]
Aw shucks, I can appreciate some help thinking up of workarounds. Haven't
had a chance to play with tl5 yet.

**Comment by rstacruz** [comment]
btw, can you try calling `onmount()` manually and see if it initializes? if so, it might be a simple dfference of TL5 using different event names

**Comment by rstacruz** [comment]
also, did you add the `$(document).on('ready page:change', onmount)` hook?

**Comment by mintuhouse** [comment]
I added the page:change hook
Tried to manually call the `$.onmount()` - still has the problem. 
I will test again tonight and let you know if I find any workaround.

**Comment by mintuhouse** [comment]
I must not have tested it properly previously. Manually calling $.onmount() seems to do the trick.
It started working after I changed 'page:change' to 'turbolinks:load'
[link](https://github.com/basecamp/turbolinks/blob/v5/lib/assets/javascripts/turbolinks/compatibility.coffee#L17) 
Thanks @rstacruz

**Comment by rstacruz** [comment]
Thank you! I knew it's just a matter of finding the right event name. I'll
update the documentation accordingly.

**Comment by mintuhouse** [comment]
I would like to document how I solved the problem of teardown with TL5 for others who may be facing similar issue.
Problem: turbolinks cache-snapshot is taken before the DOM is destroyed (ie. before MutationObserver sees the changes). Hence TL5 caches the page with widgets undestroyed & leads to double initialization

````
$(document).on('ready shown.bs hidden.bs load turbolinks:load ajaxComplete', function() {
  /* https://github.com/turbolinks/turbolinks/#detecting-when-a-preview-is-visible
   * Need not reinitialize for previews (page loaded from cache)
   * Though not really needed if onmount is triggered only via here,
   *    sometimes double initializations are happening - may be from MutationObserver
   */
  if (!document.documentElement.hasAttribute("data-turbolinks-preview")) {
    $.onmount();
  }
});
````
 
Teardown before cache as described [here](https://github.com/turbolinks/turbolinks/issues/30#issuecomment-195803051 - Teardown before-cache)
````
// Call below before initializing any onmount behaviours
(function() {
  $.onmount(document, function() {}); // Hack to get hold of Behavior internal class
  var Behavior = $.onmount.behaviors[0].constructor;
  (function(visitEnter) {
    Behavior.prototype.visitEnter = function(el) {
      registerTearDown.call(this, el);
      visitEnter.call(this, el);
    };
  }(Behavior.prototype.visitEnter));

  function registerTearDown(el) {
    var be = this;
    if (be.exit !== undefined) {
      $(document).one('gg.onmount.destroy', function() {
        if (be.exit.call(el, el[be.key]) !== false) {
          delete el[be.key];
        }
      });
    }
  };
}());

// And then trigger onmount.destroy before-cache
$(document).on('turbolinks:before-cache', function() {
  $(document).trigger('gg.onmount.destroy');
});

````

**Comment by rstacruz** [comment]
This is worth implementing into onmount itself. Let's see.

**Comment by rstacruz** [comment]
So you have to "kill" all behaviors present on the page on
turbolinks:before-cache?

**Comment by mintuhouse** [comment]
According to [this](https://github.com/turbolinks/turbolinks#preparing-the-page-to-be-cached), third-party widget tear-down has to happen `before-cache`. But current [cleanups](http://ricostacruz.com/onmount/cleanup.html) get triggered before `turbolinks:render`. So, I added an extra listener per element per behaviour which calls the `exit` function explicity on receiving the event (`gg.onmount.destroy` in my example)
Not sure if this is what you mean by kill behaviours. 
Let me know if understood something incorrectly.

**Comment by rstacruz** [comment]
Neat. I think we can implement something like onmount.teardown() to
teardown all behaviors. That should make things easier, so all that can be
done via:

$(document).on('turbolinks:before-cache', () => { onmount.teardown() })

**Comment by mintuhouse** [comment]
Having that API would make my code much cleaner. Is it ok if I try it and submit the PR?

**Comment by rstacruz** [comment]
Hell yeah, that code deserves to live upstream. you'll want to iterate through `behaviors` and their `loaded` properties. after that, it should probably be optimized.

**Comment by rstacruz** [comment]
Okay, I implemented it myself :)

**Comment by rstacruz** [comment]
Btw, here's an alternate implementation of your workaround:

```js
$(document).on('turbolinks:before-cache', function() {
  // based off of Behavior.prototype.visitExit()
  onmount.behaviors.forEach((behavior) => {
    behavior.loaded.forEach((el, i) => {
      behavior.loaded[i] = undefined
      if (behavior.exit && behavior.exit.call(el, el[behavior.key] !== false) {
        delete el[behavior.key]
      }
    })
  })
});

**Comment by rstacruz** [comment]
v1.2.0 is out. https://github.com/rstacruz/onmount/blob/master/HISTORY.md

**Comment by rstacruz** [comment]
> EDIT: Ditch :( I have to setup node, bower, many components.

BTW, it's pretty easy. As with 95% of other npm libs out there, it's simply:

```sh
git clone https://github.com/rstacruz/onmount.git
cd onmount
npm install
npm test
```

**Comment by mintuhouse** [comment]
Thanks @rstacruz - The new code looks neat
The alternate solution looks so simple. I didn't realize that loaded will give the elements on which behaviour is initialized. 
Installed npm and the dependencies. All set for next time.

**Comment by mintuhouse** [comment]
Installed the new code. Had to add the following guard in `doExit` as `be.loaded` will have `undefined` elements after each page visit
`if (typeof el === 'undefined') return`

**Comment by mintuhouse** [comment]
General question: Is it ever possible that teardown is still happening and the turbolinks starts caching the page?

**Comment by rstacruz** [comment]
are you confident that this should work for everyone?

**Comment by rstacruz** [comment]
Like this?

```diff
  Behavior.prototype.doExit = function (el, i) {
+   if (typeof el === 'undefined') return
    if (typeof i === 'undefined') i = this.loaded.indexOf(el)
    this.loaded[i] = undefined
    if (this.exit && this.exit.call(el, el[this.key]) !== false) {
      if (onmount.debug) log('exit', this.selector, el)
      delete el[this.key]
    }
  }
```

**Comment by rstacruz** [comment]
Okay, I see the problem now.
